### ISSUE TITLE
Rotating the O piece does not reset the lock delay

### ISSUE THREAD

**Issue by SashLilac** [leduyquang753/tetreml#2]
As shown in the code below, rotation of the O piece does not do anything - this includes resetting the lock delay.

https://github.com/leduyquang753/tetreml/blob/91c1ea334a482d321645d54cbdfc9d6a691c30dc/Tetriminos.js#L200-L216

**Comment by leduyquang753** [comment]
This was intentional as rotating an O would effectively do nothing and as such there is quite no reason to reset the delays. I think one doesn't need much thinking time for a square to abuse the delay timer either. But this might get changed in the future.

**Comment by SashLilac** [comment]
I see. Rotation of an O resetting lock delay is a feature in most Tetris games, so I thought I would make it known.
